[target."cfg(all())"]
rustflags = []

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+neon"]

[target."cfg(target_arch = \"aarch64\")"]
rustflags = ["-C", "target-feature=+neon"]

[profile.release]
debug = false
